import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Menu } from '../components/reusable/Menu'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=' flex justify-between items-center p-3 md:px-10 border-b-[1px]'>
          <b><h1>ALB </h1></b>
          <Menu />
        </nav>
        {children}
      </body>
    </html>
  )
}
